language: nix
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init
script: ./build.sh make test
after_success:
  - echo "DEPLOYING"
  - ls -R html
  - echo "$GIST_TOKEN" >~/.gist
  - ./build.sh push-gist publish
